/**
 * V15.0 WS7 — env-writer.
 * Helper per leggere/aggiornare `.env.local` preservando commenti e formato.
 * Backup automatico se il file esiste e ha contenuto.
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { atomicWriteFile } from '../atomic-write'
import { logger } from '../logger'

/** Path assoluto a `.env.local` nel project root (3 livelli sopra server/lib/auth/) */
function getEnvLocalPath(): string {
  // Risali da server/lib/auth/env-writer.ts a project root
  const here = path.dirname(new URL(import.meta.url).pathname)
  // strip leading slash su Windows quando from file:///C:/...
  const cleanHere = process.platform === 'win32' && here.startsWith('/') ? here.slice(1) : here
  // server/lib/auth → ../../../  → project root
  return path.resolve(cleanHere, '..', '..', '..', '.env.local')
}

/**
 * Parse esistente `.env.local` in righe + chiavi-valori.
 * Preserva commenti e righe vuote come stringhe raw.
 */
interface ParsedEnv {
  raw: string[]
  keyIndex: Map<string, number> // KEY → index in raw[]
}

async function parseEnvLocal(filePath: string): Promise<ParsedEnv | null> {
  try {
    const content = await fs.readFile(filePath, 'utf-8')
    const raw = content.split(/\r?\n/)
    const keyIndex = new Map<string, number>()
    raw.forEach((line, idx) => {
      // Match KEY=VALUE (no leading whitespace, KEY = uppercase + underscore)
      const m = /^([A-Z_][A-Z0-9_]*)=/.exec(line)
      if (m) keyIndex.set(m[1]!, idx)
    })
    return { raw, keyIndex }
  } catch (err: unknown) {
    if (err && typeof err === 'object' && 'code' in err && err.code === 'ENOENT') return null
    throw err
  }
}

/**
 * Aggiorna `.env.local` applicando un patch di chiavi-valori.
 * - Se chiave esistente: sostituisce valore (preserva ordine)
 * - Se chiave nuova: appende in fondo
 * - Backup `.env.local.backup-<ts>` se file esiste con contenuto
 * - Atomic write tramite atomicWriteFile
 *
 * Returns: path al file scritto e eventuale backup creato.
 */
export async function updateEnvLocal(
  updates: Record<string, string>
): Promise<{ path: string; backup: string | null }> {
  const filePath = getEnvLocalPath()
  const existing = await parseEnvLocal(filePath)

  let lines: string[]
  let backupPath: string | null = null

  if (existing && existing.raw.length > 0) {
    // Backup
    const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
    backupPath = `${filePath}.backup-${ts}`
    try {
      await fs.copyFile(filePath, backupPath)
    } catch (err) {
      logger.warn('[env-writer] backup failed (non-fatal):', err)
      backupPath = null
    }

    // Patch in-place
    lines = [...existing.raw]
    for (const [key, value] of Object.entries(updates)) {
      const escapedValue = escapeEnvValue(value)
      const newLine = `${key}=${escapedValue}`
      const idx = existing.keyIndex.get(key)
      if (idx !== undefined) {
        lines[idx] = newLine
      } else {
        lines.push(newLine)
      }
    }
  } else {
    // File nuovo
    lines = [
      `# .env.local generated by SAIO setup on ${new Date().toISOString()}`,
      `# Do not commit. For re-setup use the wizard at /claim or scripts/saio-init.ps1`,
      '',
    ]
    for (const [key, value] of Object.entries(updates)) {
      lines.push(`${key}=${escapeEnvValue(value)}`)
    }
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true })
  await atomicWriteFile(filePath, lines.join('\n'))
  logger.info(`[env-writer] updated ${path.basename(filePath)} with ${Object.keys(updates).length} keys`)
  return { path: filePath, backup: backupPath }
}

/**
 * Escape valore env per evitare problemi con spazi/quotes.
 * Wrap con doppi apici se contiene spazi o caratteri speciali.
 */
function escapeEnvValue(value: string): string {
  if (/[\s"#$']/.test(value)) {
    // wrap in double quotes, escape inner quotes
    const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
    return `"${escaped}"`
  }
  return value
}

/** Side effect: aggiorna anche process.env in-memory perché il server attivo veda i nuovi valori. */
export function setProcessEnv(updates: Record<string, string>): void {
  for (const [key, value] of Object.entries(updates)) {
    process.env[key] = value
  }
}
