# V15.0 WS6 — SAIO Dashboard initial setup (interactive).
# Configura email provider per magic links + JWT secret + opzioni opzionali.
# Scrive .env.local nel project root.

$ErrorActionPreference = 'Stop'

# Resolve project root (this script is in dashboard/scripts/)
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$projectRoot = Split-Path -Parent $scriptDir
$envPath = Join-Path $projectRoot '.env.local'

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  SAIO DASHBOARD — initial setup" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

if (Test-Path $envPath) {
  Write-Host ".env.local esiste già." -ForegroundColor Yellow
  $overwrite = Read-Host "  Sovrascrivere? (y/N)"
  if ($overwrite -ne 'y' -and $overwrite -ne 'Y') {
    Write-Host "Aborted." -ForegroundColor Red
    exit 0
  }
  $backup = "$envPath.backup-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
  Copy-Item $envPath $backup
  Write-Host "  Backup salvato: $backup" -ForegroundColor Gray
}

# ─────── Step 1: email provider ───────
Write-Host "[1/4] Email provider per magic links?" -ForegroundColor White
Write-Host "  1) Gmail (App Password — guida sotto)"
Write-Host "  2) Outlook / Hotmail"
Write-Host "  3) Custom SMTP (qualsiasi server con auth)"
Write-Host "  4) Resend (API key + dominio verificato)"
Write-Host "  5) Dev mode (link stampato in stdout, no email reali)"
Write-Host ""
$emailChoice = Read-Host "  Scelta [1-5]"

$envLines = @(
  "# Generated by scripts/saio-init.ps1 on $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')"
  "# Modifica con cautela. Per re-run setup: pwsh scripts/saio-init.ps1"
  ""
  "# === Path & ports (defaults sani) ==="
  "DASHBOARD_DATA_DIR=./data"
  "VITE_PORT=3030"
  "SERVER_PORT=3031"
  ""
  "# === Auth ==="
  "DASHBOARD_AUTH_REQUIRED=true"
  "DASHBOARD_AUTH_TRUST_CLOUDFLARE=true"
  "DASHBOARD_AUTH_CLAIM_TTL_MIN=5"
  ""
)

switch ($emailChoice) {
  '1' {
    Write-Host ""
    Write-Host "Gmail richiede:" -ForegroundColor Yellow
    Write-Host "  • Account Google con 2FA attivo (https://myaccount.google.com/security)"
    Write-Host "  • App Password generata (https://myaccount.google.com/apppasswords)"
    Write-Host "  • L'App Password è 16 caratteri senza spazi (es. abcdwxyzefghijkl)"
    Write-Host ""
    $gmailUser = Read-Host "  La tua email Gmail"
    $gmailPass = Read-Host "  Gmail App Password (16 char)"
    $gmailPass = $gmailPass -replace '\s', ''
    $envLines += @(
      "# === Email: Gmail SMTP ==="
      "DASHBOARD_AUTH_SMTP_HOST=smtp.gmail.com"
      "DASHBOARD_AUTH_SMTP_PORT=587"
      "DASHBOARD_AUTH_SMTP_USER=$gmailUser"
      "DASHBOARD_AUTH_SMTP_PASS=$gmailPass"
      "DASHBOARD_AUTH_FROM=$gmailUser"
      "DASHBOARD_AUTH_DEBUG_MAGIC_LINK=false"
      ""
    )
    Write-Host "  ✓ Gmail SMTP configurato" -ForegroundColor Green
  }
  '2' {
    Write-Host ""
    $outlookUser = Read-Host "  La tua email Outlook/Hotmail"
    $outlookPass = Read-Host "  Password (o App Password se 2FA attivo)"
    $envLines += @(
      "# === Email: Outlook SMTP ==="
      "DASHBOARD_AUTH_SMTP_HOST=smtp-mail.outlook.com"
      "DASHBOARD_AUTH_SMTP_PORT=587"
      "DASHBOARD_AUTH_SMTP_USER=$outlookUser"
      "DASHBOARD_AUTH_SMTP_PASS=$outlookPass"
      "DASHBOARD_AUTH_FROM=$outlookUser"
      "DASHBOARD_AUTH_DEBUG_MAGIC_LINK=false"
      ""
    )
    Write-Host "  ✓ Outlook SMTP configurato" -ForegroundColor Green
  }
  '3' {
    Write-Host ""
    $smtpHost = Read-Host "  SMTP host (es. mail.tuodominio.com)"
    $smtpPort = Read-Host "  SMTP port (587 / 465 / custom) [587]"
    if (-not $smtpPort) { $smtpPort = '587' }
    $smtpUser = Read-Host "  SMTP user"
    $smtpPass = Read-Host "  SMTP password"
    $smtpFrom = Read-Host "  From address (Enter per usare $smtpUser)"
    if (-not $smtpFrom) { $smtpFrom = $smtpUser }
    $envLines += @(
      "# === Email: Custom SMTP ==="
      "DASHBOARD_AUTH_SMTP_HOST=$smtpHost"
      "DASHBOARD_AUTH_SMTP_PORT=$smtpPort"
      "DASHBOARD_AUTH_SMTP_USER=$smtpUser"
      "DASHBOARD_AUTH_SMTP_PASS=$smtpPass"
      "DASHBOARD_AUTH_FROM=$smtpFrom"
      "DASHBOARD_AUTH_DEBUG_MAGIC_LINK=false"
      ""
    )
    Write-Host "  ✓ Custom SMTP configurato" -ForegroundColor Green
  }
  '4' {
    Write-Host ""
    Write-Host "Resend richiede:" -ForegroundColor Yellow
    Write-Host "  • Account su https://resend.com (free tier 100/giorno)"
    Write-Host "  • API key da https://resend.com/api-keys"
    Write-Host "  • Dominio verificato con DNS SPF/DKIM (per from auth@<tuo-dominio>)"
    Write-Host ""
    $resendKey = Read-Host "  Resend API key (re_...)"
    $resendFrom = Read-Host "  From address (es. auth@tuodominio.com, o 'onboarding@resend.dev' per test)"
    if (-not $resendFrom) { $resendFrom = 'onboarding@resend.dev' }
    $envLines += @(
      "# === Email: Resend ==="
      "DASHBOARD_AUTH_RESEND_API_KEY=$resendKey"
      "DASHBOARD_AUTH_FROM=$resendFrom"
      "DASHBOARD_AUTH_DEBUG_MAGIC_LINK=false"
      ""
    )
    Write-Host "  ✓ Resend configurato" -ForegroundColor Green
  }
  '5' {
    $envLines += @(
      "# === Email: DEV MODE (link in stdout) ==="
      "DASHBOARD_AUTH_DEBUG_MAGIC_LINK=true"
      ""
    )
    Write-Host "  ✓ Dev mode attivo — magic link saranno stampati in stdout" -ForegroundColor Green
  }
  default {
    Write-Host "  Scelta non valida. Aborted." -ForegroundColor Red
    exit 1
  }
}

# ─────── Step 2: Cloudflare Tunnel URL (optional) ───────
Write-Host ""
Write-Host "[2/4] Cloudflare Tunnel URL pubblico (opzionale)" -ForegroundColor White
Write-Host "  Se userai cloudflared per esporre la dashboard pubblicamente,"
Write-Host "  inserisci https://saio.tuodominio.com. Lascia vuoto per selfhost locale."
Write-Host ""
$tunnelUrl = Read-Host "  URL pubblico"
if ($tunnelUrl) {
  $envLines += "DASHBOARD_AUTH_TUNNEL_URL=$tunnelUrl"
  $envLines += ""
}

# ─────── Step 3: JWT secret ───────
Write-Host ""
Write-Host "[3/4] JWT secret (firma cookie session)" -ForegroundColor White
Write-Host "  Lascia vuoto per auto-generate (raccomandato)."
$jwtSecret = Read-Host "  JWT secret (64 hex chars, o Enter)"
if ($jwtSecret) {
  $envLines += "DASHBOARD_AUTH_JWT_SECRET=$jwtSecret"
  $envLines += ""
} else {
  Write-Host "  → Sarà auto-generato in data/auth/.jwt-secret al primo avvio" -ForegroundColor Gray
}

# ─────── Step 4: vault path (esistente, opzionale) ───────
Write-Host ""
Write-Host "[4/4] Path vault Obsidian (opzionale, può restare vuoto)" -ForegroundColor White
$vaultPath = Read-Host "  VAULT_PATH (es. C:\Users\me\vault)"
if ($vaultPath) {
  $envLines += "VAULT_PATH=$vaultPath"
  $envLines += ""
}

# ─────── Write .env.local ───────
$envLines | Set-Content -Path $envPath -Encoding UTF8
Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "  ✓ Setup completato — .env.local scritto" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host ""
Write-Host "Prossimi step:" -ForegroundColor White
Write-Host "  1. (se primo run) npm install" -ForegroundColor Gray
Write-Host "  2. npm run dev:all   # frontend (3030) + backend (3031)" -ForegroundColor Gray
Write-Host "  3. Apri il banner CLAIM TOKEN dal log backend stdout" -ForegroundColor Gray
Write-Host "  4. Browser → http://127.0.0.1:3030/claim?token=<TOKEN>" -ForegroundColor Gray
Write-Host ""
Write-Host "Per riconfigurare: pwsh scripts/saio-init.ps1" -ForegroundColor DarkGray
Write-Host ""
